### ISSUE TITLE
Drop requirements.txt

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#110]
Doing `pip install -r requirements.txt` or `pip install -e .[dev]` install the same packages. The README uses `pip install -e .[dev]`. I  would like avoid duplication of the development dependencies and remove the `requirements.txt`.

**Comment by fdiblen** [comment]
@sverhoeven we do not have requirements.txt in this repository.

**Comment by sverhoeven** [comment]
Doh
