### ISSUE TITLE
make config a dict

### ISSUE THREAD

**Issue by fdiblen** [fair-software/howfairis#112]
Config should be a dict. 
It is cleaner if we use `config.force_registry`instead of `config.merged.force_registry`.

See:
https://github.com/fair-software/howfairis/blob/8f8fc50698c1c919b4cddb98a8fed15e4564e52b/howfairis/Config.py#L88

**Comment by jspaaks** [comment]
But note that there are 3 such `dict`s, namely
1. packaged with the software
1. as part of the repo (i.e. remote)
1. somewhere on the user's system

`merged` is just the effective config resulting from superimposing these 3 configurations.

So I guess what you're asking is, how can we simplify `Config` while still being able to access the information in these 3 places?

**Comment by sverhoeven** [comment]
Correct, when reading the config I should not have to care where the values came from. I just want a simple API to read options from.

**Comment by jspaaks** [comment]
>  when reading the config I should not have to care where the values came from

Ideally, no. But do you remember trying to figure out how SSH configs were related to 
- hardcoded values
- /etc/ssh/ssh_config
- ~/.ssh/config 

That's why I see the merit of at least having access to each.

**Comment by jspaaks** [comment]
> It is cleaner if we use config.force_registry

Doesn't that imply an object with a getter? If Config is just a `dict`, it would be 

```python
config["force_registry"]
```
or 
```python
config.get("force_registry")
```

You'd need getters for all properties (and would not be able to deal with additional properties)

**Comment by jspaaks** [comment]
Is this more or less what you mean?
https://github.com/fair-software/howfairis/blob/60f0d0cc1084ba54ac509054ac8db9e07fd8d839/howfairis/config.py

So you can do 
https://github.com/fair-software/howfairis/blob/60f0d0cc1084ba54ac509054ac8db9e07fd8d839/tests/test_config.py#L12-L18

**Comment by sverhoeven** [comment]
New api is inplace
