### ISSUE TITLE
Use venv instead of virtualenv

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#118]
The developer install and release chapters in the README use `python3 -m virtualenv -p python3 venv3` command.
As of Python 3.3 the `venv` package is included in every Python installation. The `virtualenv` package has to be installed with pip. 
To reduce number of steps I would suggest to change the virtual env creation command to `python3 -m venv venv3`.

**Comment by jspaaks** [comment]
Unassigning myself so that others can take this up if they want

**Comment by jspaaks** [comment]
PR #129 was merged, closing this issue
