### ISSUE TITLE
Extra conda badges

### ISSUE THREAD

**Issue by fdiblen** [fair-software/howfairis#124]
The badges below are not supported currently. It would be good to add them as well.
https://anaconda.org/anaconda/conda-build/badges/latest_release_date.svg
https://anaconda.org/anaconda/conda-build/badges/latest_release_relative_date.svg
https://anaconda.org/anaconda/conda-build/badges/platforms.svg

**Comment by sverhoeven** [comment]
Do you have repo urls where those badges are being used?

**Comment by jspaaks** [comment]
PR #152

**Comment by fdiblen** [comment]
The badges were added in PR #152. Closing the issue.
