### ISSUE TITLE
Add test for SHA and tags

### ISSUE THREAD

**Issue by fdiblen** [fair-software/howfairis#126]
Tests are checking the default branch. It is good to have tests for SHA and tags.

**Comment by sverhoeven** [comment]
When test coverage in #50 is added we will see the need for those tests.

**Comment by jspaaks** [comment]
Blocked by #132 (Formulate a testing strategy)

**Comment by jspaaks** [comment]
PR #146 includes some of this

**Comment by jspaaks** [comment]
Done well enough to close this
