### ISSUE TITLE
create fixtures for each repo

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#127]
make a new directory, `/howfairis/fixtures/` containing python files with fixtures using one function per repository

https://github.com/fair-software/howfairis/blob/3a4051e61a42a415ea34bcbbd500a745cddacd11/tests/test_checker.py#L9-L25

**Comment by sverhoeven** [comment]
Fixtures must be discoverable by Pytest, a fixtures dir will not work. See https://docs.pytest.org/en/stable/fixture.html?highlight=conftest#conftest-py-sharing-fixtures-across-multiple-files for how to use conftest.py to share fixtures.

**Comment by sverhoeven** [comment]
Another option could be to use https://pypi.org/project/pytest-recording/ so each repo can have its own yaml file with request recordings.

**Comment by jspaaks** [comment]
Blocked by #132 (Formulate a testing strategy)

**Comment by jspaaks** [comment]
This issue might be supeseded by PR #146
