### ISSUE TITLE
Add ability to run style checks locally

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#136]
During making of a pull request I had to hear from CI that I made a error in the order of imports or broke some other prospector rule. Then I had to fix it locally and wait for the CI to complain again about something else.

It would be nice I you could run the [style checks](https://github.com/fair-software/howfairis/blob/62ed9af07d0c421e57261adc7e75e8ca4c239731/.github/workflows/tests.yml#L32-L37) before pushing.

Even nicer if errors where fixed automatically.

**Comment by sverhoeven** [comment]
I tried to write a pre-commit config

```shell
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/PyCQA/prospector
    rev: 1.3.1
    hooks:
    -   id: prospector
        additional_dependencies: ['pyroma>=2.4']
-   repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
```

Sadly the prospector hook is not behaving correctly. It gives import-errors.

**Comment by jspaaks** [comment]
https://github.com/research-software-directory/research-software-directory/blob/1837c040b4e1fb219c38213ab4bb135001c09c6f/docs/documentation-for-developers.md#running-the-superlinter-locally

**Comment by jspaaks** [comment]
PR #208 adds pre-commit hooks for both `prospector` and `isort` using the configuration like described in the README.dev.rst of that PR.

**Comment by jspaaks** [comment]
Can this be closed now that we have githooks for prospector and isort?

**Comment by fdiblen** [comment]
@fdiblen will test the hooks and close the issue if they work.

**Comment by jspaaks** [comment]
```shell
cd $(mktemp -d --tmpdir howfairis.XXXXX)
git clone https://github.com/fair-software/howfairis .
git checkout -b owinefoiwnf
touch test.md
git add test.md
git commit -m "testing precommits"
```

**Comment by jspaaks** [comment]
PR was merged, precommit was tested. Closing
