### ISSUE TITLE
Exit codes?

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#139]
The cli now exits with non-zero when a README or fair badge is missing in README.  To me having no README is not a fatal error it just mean your are non-compliant. Can we check when a non-zero exit is expected?

**Comment by jspaaks** [comment]
Related: https://github.com/fair-software/howfairis/issues/47

**Comment by fdiblen** [comment]
We only return zero if we have a README with the correct fair-software badge.
