### ISSUE TITLE
Dont need .exe on Windows

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#140]
The [documentation shows](https://github.com/fair-software/howfairis#install) you need to use `howfairis.exe` under Windows. However you can also just call `howfairis`. So the distinction between calling the tool from Linux/Mac and Windows is not really there. I would like to see the removal of the `howfairis.exe` code snippets as they make things more complicated then needed.

**Comment by jspaaks** [comment]
hm strange. I added it because it wasnt working on my windows if I recall. Worth another look I guess!

**Comment by sverhoeven** [comment]
I installed it in a miniconda environment and was I able to call it without .exe in the Conda prompt, Command prompt and PowerShell

**Comment by fdiblen** [comment]
We should check this on Windows. If it works without exe extension, we prefer it.

**Comment by jspaaks** [comment]
I checked on Windows 10 with Python 3.8, both command prompt and powershell. Using just `howfairis` works, no need for `.exe`.

I made PR #155

**Comment by sverhoeven** [comment]
No more `howfairis.exe` in README due to #155.
