### ISSUE TITLE
Use less None as default

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#144]
In the code None is used as argument default while there is better default.

For example:
1. Repo, could have `path=''` and `config_file='.howfairis.yml'`
1. Config, could have `config_file='.howfairis.yml'`
1. Compliance could have False for `repository`, `license`, `registry`, `citation` and `checklist` arguments
1. Checker, could have  `self.readme = self._get_readme() ` in constructor. 
2. .howfairis.yml, could have False for force_* options.

**Comment by jspaaks** [comment]
item 3 was implemented as part of PR #156

**Comment by jspaaks** [comment]
item 4 is not allowed by a linter we were using in the past. It said, if your instance has methods that change members of the instance, define them in the (body of the) constructor. This is to avoid introducing surprise members from methods such as `self._get_readme()`

**Comment by jspaaks** [comment]
item 5 works different than what you may expect, users can force it either `false` or `true`, or let the algorithm do its thing without any forcing (hence you need the 'unset' value `~`)

**Comment by sverhoeven** [comment]
Found another use of None in Readme.py constructor, it could use required arguments.

**Comment by sverhoeven** [comment]
Option 5 is handled in #164

**Comment by sverhoeven** [comment]
All options have been fixed already or split off into own issues.
