### ISSUE TITLE
Make check_five_recommendations return compliance

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#145]
At the moment [Checker.check_five_recommendations(()](https://github.com/fair-software/howfairis/blob/0f977da1d7a97f70b5aa7f6178eb22aa8dc030d7/howfairis/Checker.py#L137) returns the checker itself. 
To get the compliance you have to do `compliance = checker.compliance`.

It would be more clear to me when `check_five_recommendations` returns the compliance object directly.

**Comment by jspaaks** [comment]
PR #156

**Comment by sverhoeven** [comment]
Completed in #156
