### ISSUE TITLE
Export shadow

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#147]
The `__init__.py` overwrites the export of the `Checker.py` module. Making it impossible to import the Checker module.

Now
```python
from howfairis import Checker # class
from howfairis.Checker import Checker # class
```

Without Checker in __all__ in __init.py
```python
from howfairis import Checker # module
from howfairis.Checker import Checker # class
```

One solution would be to use lowercase for modules as specified in [PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names).

**Comment by fdiblen** [comment]
we will follow pep8 conventions.

we change `__init__` imports like:
```python
from howfairis.checker import Checker
```
to import the module:
```python
from howfairis import Checker
```

**Comment by jspaaks** [comment]
PR #149 was merged, closing
