### ISSUE TITLE
Check scripts running from a URL

### ISSUE THREAD

**Issue by c-martinez** [fair-software/howfairis#16]
At the moment all check scripts run under the assumption that they have access to the repository of the code being evaluated (it is checked out on the same directory). In the future, it would be desirable if the initial assumption is that the check scripts start form the assumption that they receive the URL of the repo being checked.

**Comment by jspaaks** [comment]
Fixed in 410fc6ba9f6f12e50a3aaf923426b76b291ed57f, closing this issue.
