### ISSUE TITLE
rename `vcs_platform` in license_mixin.py

### ISSUE THREAD

**Issue by fdiblen** [fair-software/howfairis#161]
Rename `vcs_platform` to `version_control_system` in `howfairis/mixins/license_mixin.py`

See:
https://github.com/fair-software/howfairis/pull/146/files#diff-36f82e6d0e9dd22c212dc4f9ce9073d36d32c8ebd3415929ad24d68ef5a522e0R3

**Comment by jspaaks** [comment]
or maybe something like `hosts` or `domains` or `supported_domains`

**Comment by fdiblen** [comment]
we decided to use `code_repository_platforms`
