### ISSUE TITLE
force value False unwanted

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#164]
The config has a `force_*` property for each recommendation.
Currently, the value can be 

1. True: force compliance without performing check
2. False: force non-compliance without performing check
3. None: perform check

I could not come up with a repo which needs to use the `False` value. As howfairis is then reporting a false Positive which should be fixed and not be overwritable.

I would like to propose we make the value be
1. True: force compliance without performing check
2. False: perform check

This would make `force*` props much more intuitive to me.

**Comment by jspaaks** [comment]
So, `skip_checklist_checks`, `skip_registry_checks`, etc.? with defaults `False`

**Comment by sverhoeven** [comment]
Yes, `skip_<recommendation>_checks` is a good name. Let's go with that.

**Comment by jspaaks** [comment]
PR #207 might be what we want

**Comment by jspaaks** [comment]
PR was merged, closing
