### ISSUE TITLE
Feedback on force usage

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#165]
When `force_registery: True` is used in the configuration you will get the following output:

```text
(3/5) registry: force True
```

This is not very user friendly, can it be changed in something like

```text
(3/5) registry:
✓ forced_by_configuration
```

When  `force_registery: False` I would like to see something like
```text
(3/5) registry:
 × forced_by_configuration
```

**Comment by jspaaks** [comment]
PR https://github.com/fair-software/howfairis/pull/207 might be what we want

**Comment by jspaaks** [comment]
PR was merged, closing
