### ISSUE TITLE
does Checker need repo as its argument

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#172]
Since it already has `config`, which in turn has `repo`

This can lead to weird code like

```python
repo = Repo("https://github.com/fair-software/badge")
config = Config(repo)
return Checker(config, repo)
```

This probably means we have to add a `self.repo = repo` in `Config.__init__` though.

**Comment by sverhoeven** [comment]
Hiding repo makes it harder for me to understand what the checker does.

**Comment by sverhoeven** [comment]
Alternatively we could make config optional. So checker makes config based on repo when config is not given.

```python
repo = Repo("https://github.com/fair-software/badge")
checker = Checker(repo=repo)
```

**Comment by sverhoeven** [comment]
See alternate at #194

**Comment by jspaaks** [comment]
PR #201 might be a solution

**Comment by jspaaks** [comment]
PR was merged, closing
