### ISSUE TITLE
Dont abbreviate format to fmt

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#173]
The Readme class uses `fmt` to describe the format of the README aka Markdown or RestructuredText. Abbreviating `format` to `fmt` seems unneeded. It would help readability to use no abbreviations where possible.

**Comment by jspaaks** [comment]
Agreed, but:

```shell
$ python
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> format
<built-in function format>
>>> 

```

**Comment by sverhoeven** [comment]
Let's rename it to `file_format`.

**Comment by jspaaks** [comment]
PR was merged, closing
