### ISSUE TITLE
Use config_file='.howfairis.yml'

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#175]
The config_file is None by default in Repo and Config class. The default is '.howfairis.yml' in some places. It would be nice if that would be visible more clearly.

Separated  from #144, there option 1 and 2

**Comment by jspaaks** [comment]
related PR #200

**Comment by jspaaks** [comment]
When working on this issue, be aware that there are 3 places where `user_config_filename` defaults are set: 

1. in the `Click` decorator for `howfairis/cli.py::cli`
2. in the cli function signature `howfairis/cli.py::cli`
3. in the constructor for `Checker` (PR #201) or **`Config`** ([master](https://github.com/fair-software/howfairis/blob/dac5e413c75c6ac9d7bf474e73b13cabd08dfac9/howfairis/config.py))

(I think it makes sense to have the same default for these 3 places)

And that there are 3 places where `repo_config_filename` defaults are set: 
1. in the `Click` decorator for `howfairis/cli.py::cli`
2. in the cli function signature `howfairis/cli.py::cli`
3. in the constructor for `Checker` (PR #201) or **`Repo`** ([master](https://github.com/fair-software/howfairis/blob/dac5e413c75c6ac9d7bf474e73b13cabd08dfac9/howfairis/config.py))

(I think it makes sense to have the same default for these 3 places)

The defaults are currently `None` in all of these places, and there is code that depends on this. For example, to only provide feedback when users have specified a value for either of these config file names.

**Comment by sverhoeven** [comment]
Fixes here will require updates for #229

**Comment by sverhoeven** [comment]
* `Checker.user_config_filename` is used as boolean whether to read a file and as the name of that file. No changes are required for that as when None is used to ignore user config file and when filled string that file is read.
* Checker.repo_config_filename` and cli(repo_config_filename) still have None as default which can be swapped to `.howfairis.yml`

**Comment by sverhoeven** [comment]
PR #246 fixed repo_config_filename
