### ISSUE TITLE
Make Checker.readme non-None

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#176]
In Checker constructer the readme attribute is first None and then set to a Readme object.

https://github.com/fair-software/howfairis/blob/c2af709834fb82782ccf31d71a897193e381c54f/howfairis/checker.py#L40-L43

It would be nicer if it was set once with something like `self.readme = self._get_readme()` 

Separated from #144 option 4

**Comment by jspaaks** [comment]
PR #177

**Comment by jspaaks** [comment]
PR was merged, closing
