### ISSUE TITLE
Investigate PresQT and friends

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#180]
Investigate [Preservation Quality Tools and RESTful Services to Improve Preservation and Re-use of Research Data & Software]( https://presqt.readthedocs.io/en/latest/) aka PresQT. PresQT integrates with [fairsharing](https://fairsharing.github.io/FAIR-Evaluator-FrontEnd/#!/#%2F!%2F) and [FAIRshake](https://fairshake.cloud//).

See if howfairis can learn something from it and its friends.

**Comment by c-martinez** [comment]
@fdiblen & I attended a [presentation by them during CW21](https://software.ac.uk/cw21/mini-workshops-and-demo-sessions#2.4). We could contact Sandra Gesing if required.

I am not very sure there was any direct connection with howfairis at this point. @fdiblen -- what was your impression?

**Comment by fdiblen** [comment]
After learning more about PresQT I decided that it is not really related to howfairis. Closing the issue.
