### ISSUE TITLE
add GitHub Action example to README

### ISSUE THREAD

**Issue by fdiblen** [fair-software/howfairis#181]
In https://github.com/fair-software/badge use of howfairis in a GitHub action is shown. We should point to this repository in the documentation. It is also a good idea to add an example in this repository as well.

**Comment by jspaaks** [comment]
>  It is also a good idea to add an example in this repository as well.

Should go in the GitHub Action repo IMO

**Comment by fdiblen** [comment]
We will add a link to the github action and its repository.
