### ISSUE TITLE
Test the release from test.pypi.org

### ISSUE THREAD

**Issue by fdiblen** [fair-software/howfairis#195]
Run the following tests before releasing:
- [x] livetests
- [x] docker image
- [x] install the package from test.pypi.org and test it using a few random repos

https://github.com/fair-software/howfairis/blob/master/README.dev.rst#making-a-release

**Comment by jspaaks** [comment]
Also check you can get a wheel and a source distribution (issue #71; https://github.com/fair-software/howfairis/pull/143#issuecomment-773237843)

**Comment by fdiblen** [comment]
We followed the instructions and have taken some notes. We will create new issues for these improvements.
