### ISSUE TITLE
Add module for workarounds?

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#216]
e.g.

- `howfairis/workarounds/__init__.py`
- `howfairis/workarounds/github_caching.py` (Erik's work from #153 could go here)
- `howfairis/workarounds/remove_rst_comments.py`
- `howfairis/workarounds/find_bitbucket_license.py` 
- `howfairis/workarounds/find_gitlab_license.py` (BeautifulSoup workaround)
- etc

And then in the rest of howfairis, you could do, e.g.

```python
from howfairis.workarounds import remove_rst_comments
```

**Comment by jspaaks** [comment]
Something like PR #220

**Comment by fdiblen** [comment]
We all liked the approached. This needs more grooming.

**Comment by jspaaks** [comment]
Not sure what was meant with grooming, but the PR was merged, so closing
