### ISSUE TITLE
(how) do we unit test functions that print something

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#218]

**Comment by sverhoeven** [comment]
Pytest can capture output, see https://docs.pytest.org/en/stable/capture.html#accessing-captured-output-from-a-test-function

**Comment by jspaaks** [comment]
I like that `capsys` thing, should we use it /can we use it as a context, like the `.disabled()` example?

**Comment by sverhoeven** [comment]
@eriktks also used it at https://github.com/fair-software/howfairis/blob/show-readme-date-57/tests/test_github_caching.py#L10-L30

**Comment by sverhoeven** [comment]
We like to use the approach of pytest to capture output. Unwanted output can ignored if needed. Lets use default (fd) capturing method.

**Comment by sverhoeven** [comment]
Lets go with option 2

**Comment by jspaaks** [comment]
We have found an approach, closing

**Comment by sverhoeven** [comment]
To test cli method we can use [click testing](https://click.palletsprojects.com/en/7.x/testing/) see https://github.com/fair-software/howfairis/blob/4dfd444737ff628b6afd27200e8351f3e992ed09/tests/github/repo1/test_cli_no_args.py#L2 it captures output and exit codes.
