### ISSUE TITLE
Dont reexport in howfairis/*/__init__.py

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#226]
Having different ways to import a method/class to me is maintenance headache (I will forget to put new things in it). I propose to only re-export in `howfairis/_init__py` so it easy to use as a library. And to empty the ` howfairis/*/__init__.py` files.

This will change imports like
```
from .workarounds import remove_comments_rst
```
into
```
from .workarounds.remove_comments_rst import remove_comments_rst
``

**Comment by jspaaks** [comment]
Let's try it, see how far we get

**Comment by jspaaks** [comment]
PR was merged, closing
