### ISSUE TITLE
fill in tests for tests/github/fair_software/badge/test_checker_with_noreason_user_config.py

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#227]
spawned from PR #224

https://github.com/fair-software/howfairis/blob/bb246019abbb510d19a4642cb51b6596a736ea1d/tests/github/fair_software/badge/test_checker_with_noreason_user_config.py

**Comment by jspaaks** [comment]
also tests/github/fair_software/badge/test_checker_with_reasonable_user_config.py

**Comment by sverhoeven** [comment]
All tests for both test classes have been implemented in #224
