### ISSUE TITLE
add/update documentation for exceptions

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#234]
- [x] HowfairisException
- [x] GetDefaultBranchException

**Comment by sverhoeven** [comment]
For me the documentation of both exceptions is already good enough. See https://howfairis.readthedocs.io/en/latest/apidocs/howfairis.exceptions.get_default_branch_exception.html and https://howfairis.readthedocs.io/en/latest/apidocs/howfairis.exceptions.howfairis_exception.html

**Comment by jspaaks** [comment]
Agreed, I'm calling this done
