### ISSUE TITLE
Zenodo badge not identified

### ISSUE THREAD

**Issue by PabRod** [fair-software/howfairis#27]
I've just tried this after the presentation of @jspaaks at the eScience Center with my [own repo](https://github.com/PabRod/rolldown). For some reason, it doesn't identify my Zenodo badge.

```
$ howfairis https://github.com/PabRod/rolldown

Checking compliance with fair-software.eu...
Running for https://github.com/PabRod/rolldown

(1/5) repository
      ✓ has_open_repository
(2/5) license
      ✓ has_license
(3/5) registry
      × has_pypi_badge
      × has_cran_badge
      × has_conda_badge
      × has_bintray_badge
      × is_on_github_marketplace
(4/5) citation
      × has_zenodo_badge
      × has_citationcff_file
      × has_citation_file
      × has_zenodo_metadata_file
      × has_codemeta_file
(5/5) checklist
      × has_core_infrastructures_badge
      × has_sonarcloud_badge

Calculated compliance: ● ● ○ ○ ○

While searching through your README.md, I did not find the expected badge:
[![fair-software.eu](https://img.shields.io/badge/fair--software.eu-%E2%97%8F%20%20%E2%97%8F%20%20%E2%97%8B%20%20%E2%97%8B%20%20%E2%97%8B-orange)](https://fair-software.eu)

```

**Comment by jspaaks** [comment]
Hi @PabRod, thanks for giving this tool a whirl, and taking the time to file the report.

It looks like your badge uses a different endpoint that what the regex checks for. ``howfairis==0.5.0`` checks for URLs like 
``https://zenodo.org/badge/DOI/10.5281/zenodo``, but your readme uses ``https://zenodo.org/badge/<a number>.svg``.

I've created PR https://github.com/fair-software/howfairis/pull/29 that should fix this issue.
