### ISSUE TITLE
dont show cant-remove-comment warning for rst file without comments

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#272]
if we would have a simple way of checking whether a given RST file has comments, we wouldnt need to always print the warning for RST READMEs

**Comment by sverhoeven** [comment]
In closed PR #150 I used a RST parser ([docutils](https://pypi.org/project/docutils/)) to filter out comments. However the produced RST was to mangled. But the visitor pattern at https://github.com/fair-software/howfairis/blob/612c849c6115fa7a51147cef3aec4dc37ab7e6eb/howfairis/readme.py#L26 could be used to detect comments.
