### ISSUE TITLE
testing: why do we need list_files_from_local_data?

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#275]
I'd prefer to stick to only its `load_*` sibling if we can

**Comment by sverhoeven** [comment]
To test the `user_config_filename` argument in Checker() a path to a file is required. The `load*` method does not return a path you can use, but its key is relative to the user-files directory. So you would need to convert the key returned by load* method back to a full path.

Alternatively we could also write a new file, based on the return of the load method, for the test, but that seems unnecessary complicated.

**Comment by jspaaks** [comment]
OK thanks for elaborating
