### ISSUE TITLE
clean up branches

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#278]
https://github.com/fair-software/howfairis/branches/all

reminders: 
1. branch names should start not end with issue number
2. delete your own branch after merging or closing

**Comment by sverhoeven** [comment]
I have removed my branches, where ever I though the work in the branhc could still be useful I embedded the commit in an issue.

Branch naming is not defined in CONTRIBUTING.rst or README.dev.rst . If you want to enforce branch naming please write it down somewhere.

**Comment by fdiblen** [comment]
I have only a single branch with a draft PR.

**Comment by jspaaks** [comment]
notify @eriktks you still have an old branch lingering, please remove
