### ISSUE TITLE
check that OpenSSF badges are recognized

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#359]
Core Infrastructures project changed its name, might have broken the correct idnetification of these badges

**Comment by benvanwerkhoven** [comment]
Can confirm, I just added the OpenSSF badge to Kernel Tuner. It is correctly recognized by howfairis.

**Comment by mattkretz** [comment]
I confirm the name change broke *new* badges. Existing badges with the old URL continue to work (as badge, link, and getting recognized by howfairis). However, the latest badge I pasted into a README.md is *not* recognized:
```
[![OpenSSF Best Practices](https://www.bestpractices.dev/projects/9447/badge)](https://www.bestpractices.dev/projects/9447)
```

I have a PR ready to resolve this issue, but the contribution guidelines require to discuss here first.

**Comment by mattkretz** [comment]
ping @c-martinez OK if I submit a PR for this as well? (https://github.com/fair-software/howfairis/commit/aecb9c355b77f808b0ee56c383b8c59db80bc1cc)
