### ISSUE TITLE
Support for maven-badges.herokuapp

### ISSUE THREAD

**Issue by vedran-kasalica** [fair-software/howfairis#363]
I have Step **"(3/5) registry"** failing because the check failed to recognise a badge generated using [maven-badges.herokuapp](https://github.com/softwaremill/maven-badges) project. See my badge [here](https://maven-badges.herokuapp.com/maven-central/io.github.sanctuuary/APE/badge.svg). 

This could be easily fixed by adding support for the[ **herokuapp** format](https://github.com/softwaremill/maven-badges#usage).

**Comment by jspaaks** [comment]
Hi Vedran, thanks for making the issue. Note that `howfairis` development is on hold for the moment, so this might not be implemented soon

**Comment by vedran-kasalica** [comment]
Hi Jurriaan, thanks for the reply. I opened PR #364 with a fix (it was a small change), but I understand that it might require time to review it.
Cheers
