### ISSUE TITLE
check_badge should not system exit

### ISSUE THREAD

**Issue by vsoch** [fair-software/howfairis#47]
If a user wants to use this library programatically, e.g., run over many repositories, it would be ideal for the check_badge function to not sys.exit(0), but instead to return True or False. For the case of the client, the sys.exit would go after this function call. I can put in a pull request with this suggested change if you think it's a good idea!

**Comment by jspaaks** [comment]
Hi Vanessa,
the sysexits are only in the CLI not the (rest of the) library, right? I believe I'm right in saying that they were necessary to get green or red status when running as part of GitHub Actions.

**Comment by vsoch** [comment]
The use case that I have in mind is this one https://rseng.github.io/rseng/software/howfairis#why-is-it-useful, or any general need to import and run the function (and the sys.exit is unexpected). If you need the client to exit for [these tests](https://github.com/fair-software/howfairis/blob/master/clitests/script.sh). For the non zero exits, it would be okay to exit there (some raise errors and pass up to calling function, but an exit isn't a crazy idea). But for [this exit](https://github.com/fair-software/howfairis/blob/master/howfairis/cli.py#L46) where the client is successful, it would kill two birds with one stone to put it [here](https://github.com/fair-software/howfairis/blob/master/howfairis/cli.py#L107), that way the exit happens for the client but the function is usable outside of it.

**Comment by jspaaks** [comment]
PR #84

**Comment by jspaaks** [comment]
PR was merged, closing
