### ISSUE TITLE
GitHub "master" becomes "main"

### ISSUE THREAD

**Issue by florian-huber** [fair-software/howfairis#48]
I realized that GitHub recently switched from ``master`` to ``main`` branch names for new repos.
That led to the following for me: ``Did not find a README[.md|.rst] file at https://raw.githubusercontent.com/iomega/ms2query/master/`` while it should actually have looked in the ``main`` folder.

[Repo I ran it for was: ``https://github.com/iomega/ms2query``]

**Comment by florian-huber** [comment]
Ok, just saw that I could run ``howfairis https://github.com/iomega/ms2query --branch main``, but if ``main`` becomes the new standard on GitHub than it would still be nice to be included automatically I guess.

**Comment by jspaaks** [comment]
Agreed, this should be added

**Comment by jspaaks** [comment]
maybe we can first ask the github api what the default branch is for the repo if the user didn't specify it

**Comment by jspaaks** [comment]
PR #92

**Comment by jspaaks** [comment]
PR was merged, closing
