### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#49]
[currently](https://github.com/fair-software/howfairis/tree/d82eb0f92620f066f28bb5083eb3097717187606) we only have one dummy test

To discuss: which framework to use?

**Comment by sverhoeven** [comment]
I would like to use [Pytest](https://docs.pytest.org/en/stable/index.html) as it can parameterize tests and is also used in [our template](https://github.com/NLeSC/python-template/blob/55129e224e7820840958367b2757ca410ccf875a/%7B%7Bcookiecutter.project_slug%7D%7D/setup.py#L66).

**Comment by sverhoeven** [comment]
This could be quite large task. I would like to start with tests that show how you would used it as a library. So start with `Checker.check_five_recommendations()` (possibly with mocked http requests).

**Comment by jspaaks** [comment]
Before doing any coding, make a plan here first and reach consensus with the team.

**Comment by jspaaks** [comment]
For now constrain to just writing unit tests of python code of the library (not anything from `cli.py`).

**Comment by sverhoeven** [comment]
Added some tests in #109, to add more tests should be part of #50 and other PRs. Closing this issue.
