### ISSUE TITLE
Add code coverage calculation

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#50]
to help steer our efforts for #49

**Comment by sverhoeven** [comment]
* [ ] The coverage deps should be added to `setup.py:extras_require:dev` list.
* [ ] The code coverage should be generated while running tests in a GitHub workflow job. 
* [ ] The coverage report should be hosted somewhere (SonarCloud, Codacy, codecov, etc., see #53). 
* [ ] The coverage report hoster should also have a coverage badge which should be added to this repos README.

**Comment by jspaaks** [comment]
Limit to unit tests only

**Comment by sverhoeven** [comment]
Coverage was added in #142
