### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#51]

**Comment by sverhoeven** [comment]
Would this be 
1. [ ] docstrings in code
2. [ ] setup https://howfairis.readthedocs.io to document how it can be used as a CLI or library.

**Comment by jspaaks** [comment]
https://github.com/fair-software/howfairis/issues/51#issuecomment-766832645 Yes both

**Comment by jspaaks** [comment]
Do public API first

**Comment by sverhoeven** [comment]
The docstring can be in several different formats, see https://realpython.com/documenting-python-code/#docstring-formats . Which do we prefer?

1. Numpy
2. Google
3. reStructuredText

**Comment by sverhoeven** [comment]
Decided to use Google docstring format

**Comment by sverhoeven** [comment]
The docs badge is green. 

All the classes/methods used below have docstring.
```python
repo = Repo('https://github.com/fair-software/howfairis')
checker = Checker(Config(repo),repo).check_five_recommendations()
checker.badge
```
Enough was done to complete this issue.
