### ISSUE TITLE
Add code quality checks

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#53]
~~e.g.~~ sonarcloud (example output: https://sonarcloud.io/dashboard?id=matchms_matchms)

**Comment by eriktks** [comment]
I have tried to add howfairis to sonarcloud but it seems sonarcloud has no access. Is this something that Jurriaan should allow (in the fair-software organization giving permission to sonarcloud under settings/third-party access)?

**Comment by sverhoeven** [comment]
@eriktks,  I think it did not work for you because you are not a public member of the organization.

**Comment by sverhoeven** [comment]
Sonarcloud analysis was added in PR #142
