### ISSUE TITLE
CII best practices is not recognized

### ISSUE THREAD

**Issue by svenvanderburg** [fair-software/howfairis#54]
If I run 
```
howfairis https://github.com/fair-workflows/nanopub
```
I get:
```
Checking compliance with fair-software.eu...
url: https://github.com/fair-workflows/nanopub
(1/5) repository
      ✓ has_open_repository
(2/5) license
      ✓ has_license
(3/5) registry
      × has_ascl_badge
      × has_bintray_badge
      × has_conda_badge
      × has_cran_badge
      × has_crates_badge
      × has_maven_badge
      × has_npm_badge
      ✓ has_pypi_badge
      × has_rsd_badge
      × is_on_github_marketplace
(4/5) citation
      × has_citation_file
      ✓ has_citationcff_file
      × has_codemeta_file
      × has_zenodo_badge
      × has_zenodo_metadata_file
(5/5) checklist
      × has_core_infrastructures_badge
      × has_sonarcloud_badge

Calculated compliance: ● ● ● ● ○

Expected badge is equal to the actual badge. It's all good.
```
It does not detect the CII badge that the project has.

**Comment by svenvanderburg** [comment]
I worked around it using the `.howfairis.yml` conf file and adding:
```
force:
  checklist: true  # The project has a CII software checklist badge, but it is not recognized by howfairis
```

You could reproduce this by forking https://github.com/fair-workflows/nanopub and removing that configuration file.

**Comment by jspaaks** [comment]
Hey Sven, thanks for the nice bug report. Glad you found the workaround. Just an FYI: your workaround will need a slight change once PR https://github.com/fair-software/howfairis/pull/46 is merged. Hopefully, we'll be able to fix this bug before then (and you can `git rm .howfairis.yml`).

**Comment by jspaaks** [comment]
@svenvanderburg could you run `howfairis --version` and post the output here please?

**Comment by svenvanderburg** [comment]
version: 0.11.0

**Comment by svenvanderburg** [comment]
It seems like github mixed up my code... 🤦 

Haha, I have literally no clue how this did not work at that moment apart from that brain was not functioning.

So please feel free to close this issue! Sorry for wasting your time (although I helped you find #55 ;) )

**Comment by jspaaks** [comment]
> It seems like github mixed up my code... facepalm

Aha, now I remember what may cause this (better late than never): there is a few minutes delay between what you see on github.com and what howfairis gets from raw.githubusercontent.com. 

No worries about wasting my time BTW this is just part and parcel of releasing software into the wild, and it can lead to useful feedback, as it did here.
