### ISSUE TITLE
Codacy not good enough?

### ISSUE THREAD

**Issue by LourensVeen** [fair-software/howfairis#59]
For check number 5, howfairis wants to have either a Core Infrastructure badge or a Sonarcloud badge. I'm using Codacy for automatic linting. Is there some reason that Sonarcloud is acceptable and Codacy isn't? If not, can Codacy be added?

**Comment by jspaaks** [comment]
Hi Lourens, thanks for making this issue. When I was implementing checks based on these badges, I started wondering if the sonarcloud badge (and codacy badge, for that matter) even falls within the definition as stated on https://fair-software.nl/recommendations/checklist/. I'm on the fence on this. At the moment I'm leaning more towards removing the SonarCloud badge test actually. This isn't to say that SonarCloud, Codacy, CodeClimate, SonarQube, PMD, Codecov, Scrutinizer, or any of the [other services](https://github.com/marketplace/category/code-quality) aren't a good practice --they are-- but perhaps not within the definition of fair-software.nl's checklist recommendation.

See also https://github.com/fair-software/howfairis/issues/30

Note that howfairis v0.12 allows for overriding the analysis by adding a file ``.howfairis.yml`` in the root of the repository, e.g. 

```yaml
# Force checklist True because I'm using Codacy
force_checklist: true 
```

Hope this helps you!

**Comment by jspaaks** [comment]
For now, we decided that codacy does not meet the requirements from fair-software.eu, hence implementation of this is not foreseen.

**Comment by LourensVeen** [comment]
Okay, yes, I guess removing SonarCloud makes more sense than adding Codacy actually.
