### ISSUE TITLE
Read config file from global location

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#61]
Now tool reads `.howfairis.yml` file in current working directory. It would be nice if it could find a config file in a global location so I don't have to `cd` to some place first. Global location could be `/etc/howfairis.yml` or `~/.config/howfairis/config.yml`.

**Comment by sverhoeven** [comment]
In the help it says `The configuration file needs to be on the remote` so this issue is probably not inline with the design decisions of the tool. 

Why was it chosen to have a config file remotely?

**Comment by jspaaks** [comment]
The configuration file model was recently changed such that the python module comes packaged with its own default config file. This can be (partially) overwritten by including an optional file in the repository (default: .howfairis.yml in the root of the repo). The result of the overwrite can subsequently be (partially) overwritten by including a file on the local file system, e.g. either a global one or a local one.

For reference, the relevant code is here: https://github.com/fair-software/howfairis/blob/0.12.0/howfairis/Config.py

As to 

> Why was it chosen to have a config file remotely?

, I think there can be good reasons to override one or more checks. For example if somebody includes a custom checklist as a MarkDown table in their ``README.md`` or as ``checklist.md``, that would not be found by a `howfairis` analysis, even though it complies with the recommendations from https://fair-software.nl/recommendations/checklist.

**Comment by sverhoeven** [comment]
Agree its more about the repo owner showing he/she is fair then someone checking if repos are fair.
