### ISSUE TITLE
Conda badge missed

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#68]
On https://github.com/xtensor-stack/xtensor-fftw there are the following badges

```markdown
[![Anaconda-Server Badge](https://anaconda.org/conda-forge/xtensor-fftw/badges/version.svg)](https://anaconda.org/conda-forge/xtensor-fftw)
[![Anaconda-Server Badge](https://anaconda.org/conda-forge/xtensor-fftw/badges/downloads.svg)](https://anaconda.org/conda-forge/xtensor-fftw)
```

However running `howfairis https://github.com/xtensor-stack/xtensor-fftw` results in `      × has_conda_badge`. So conda badge is not found. I expected it to find the badge and report `✓ has_conda_badge`.

**Comment by jspaaks** [comment]
I guess these links could be added by extending the list of regex'es here 

https://github.com/fair-software/howfairis/blob/159d12791c13a567adfa21cc5f151fd563b8a2f0/howfairis/mixins/RegistryMixin.py#L39-L40

**Comment by jspaaks** [comment]
Assigned @eriktks because he is already working on this; see PR #88

**Comment by eriktks** [comment]
Fixed by PR #88
Spawned a new issue #96

**Comment by jspaaks** [comment]
Reopening because we still need to do what it says here https://github.com/fair-software/howfairis/issues/68#issuecomment-764579539

Probably something like:

```python
 regexes = [r"https://anaconda\.org/.*/.*/badges/installer/conda\.svg", 
            r"https://anaconda\.org/.*/.*/badges/version\.svg",
            r"https://anaconda\.org/.*/.*/badges/downloads\.svg"
            r"https://img\.shields\.io/conda/.*"]
```

I know the first 3 regexes can be collapsed but I personally think this is clearer.

**Comment by jspaaks** [comment]
PR #119

**Comment by jspaaks** [comment]
PR was merged, closing
