### ISSUE TITLE
Sync Python version in test with setup.py

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#70]
The [tests on CI](https://github.com/fair-software/howfairis/blob/master/.github/workflows/tests.yml#L14) are on Python 3.6/3.7/3.8. However in the [setup.py](https://github.com/fair-software/howfairis/blob/master/setup.py#L32-L34) Python 3.5/3.6/3.7 are supported.

Can those Python versions be made more the same?

**Comment by jspaaks** [comment]
3.5 has been dropped, but let's add 3.6, 3.7, 3.8, 3.9

see also #80
