### ISSUE TITLE
Publish pure Python wheel on PyPI

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#71]
Only the source tarball is now published on PyPI. It would be nice to also publish as [wheel](https://packaging.python.org/guides/distributing-packages-using-setuptools/#wheels).

**Comment by fdiblen** [comment]
The workflow of matchms can be re-used for that.

See https://github.com/matchms/matchms/blob/master/.github/workflows/CI_publish_pypi.yml

**Comment by jspaaks** [comment]
The (only) purpose of this would be to speed up install for users, correct?

Reading from your link, we would need to create a Pure Python Wheel (I don't want to deal with Python 2 anymore, what say you?).

> The workflow of matchms can be re-used for that.

The workflow Faruk links doesn't test the package from a test server like test.pypi.org though.

Additionally I'm wondering if we can formalize some of the procedure from https://github.com/fair-software/howfairis/blob/0.12.0/README.rst#making-a-release in a user-triggered workflow that results in one or two artefacts, which developers can then download for testing before making a release.

**Comment by sverhoeven** [comment]
Wheel has other advantages than speed, see https://pythonwheels.com/

**Comment by sverhoeven** [comment]
Closure of issues is blocked by #138

**Comment by jspaaks** [comment]
Should we close this?

**Comment by sverhoeven** [comment]
Will be done as part of milestone
