### ISSUE TITLE
Ignore comments in README.rst

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#72]
[Comments](
https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#comments) in reStructuredText Markup are not ignored. Only the HTML comments are [ignored](https://github.com/fair-software/howfairis/blob/master/howfairis/Checker.py#L42). When not using `--include-comments` option I expected comments in README.rst files also to be ignored by default.

**Comment by sverhoeven** [comment]
Watch out: The `..` used for comments is not exclusive for comments and can be multi-line.

**Comment by jspaaks** [comment]
> When not using --include-comments option I expected comments in README.rst files also to be ignored by default.

Agree

**Comment by jspaaks** [comment]
If we cant decide based on the raw files, consider using the HTML/rendered version from github/gitlab

**Comment by sverhoeven** [comment]
Tried to remove comments in #150 with a rst parser, but did not manage to pass tests.

**Comment by sverhoeven** [comment]
Let's show warning that rst can not ignore comments.

**Comment by sverhoeven** [comment]
Warning is good enough for now.
