### ISSUE TITLE
Mention in the README which Python versions are supported

### ISSUE THREAD

**Issue by fdiblen** [fair-software/howfairis#73]
Mention supported Python versions in README.md

**Comment by sverhoeven** [comment]
Besides of documenting we could also look if we can raise an error when a too old Python is used. For example see `Fail early in setup.py` chapter on https://python3statement.org/practicalities/

**Comment by jspaaks** [comment]
I would prefer to do this https://github.com/fair-software/howfairis/issues/73#issuecomment-767477690 if we can get that working, otherwise, default to adding a line in the README.

**Comment by jspaaks** [comment]
PR #158 (doesn't include Stefan's suggestion though)

**Comment by jspaaks** [comment]
Can this be closed?

**Comment by fdiblen** [comment]
Python versions are listed in a badge.
