### ISSUE TITLE
Improve cli tests

### ISSUE THREAD

**Issue by fdiblen** [fair-software/howfairis#76]
Currently cli is tested using a shell script. We should improve the tests. See the link below for some ideas.
https://realpython.com/python-cli-testing/

**Comment by sverhoeven** [comment]
In the unit tests at https://github.com/fair-software/howfairis/blob/c803c81fa4492c3830babc97e7ccc2e74c8b48ac/tests/github/repo1/test_cli_no_args.py#L31

The cli main function is tested is this good enough?

**Comment by jspaaks** [comment]
>  is this good enough?

Yes or else we have to formulate a close condition for this issue

**Comment by fdiblen** [comment]
We have enough tests.
