### ISSUE TITLE
Document the config file

### ISSUE THREAD

**Issue by fdiblen** [fair-software/howfairis#78]
The default configuration file is ".howfairis.yml". We should explain
- what this file is
- why it is needed
- the content of the file
See https://github.com/fair-software/howfairis/blob/master/howfairis/data/.howfairis.yml

**Comment by sverhoeven** [comment]
In https://github.com/fair-software/howfairis/pull/188#pullrequestreview-588535505 @jspaaks wanted to take a step back. So until it is clear what are the shortcomings of the current explaination this is issue is blocked.

**Comment by fdiblen** [comment]
The config file is explained in README.md. Closing this issue.
