### ISSUE TITLE
Support Python 3.8 and 3.9

### ISSUE THREAD

**Issue by fdiblen** [fair-software/howfairis#80]
The latest stable version of Python is 3.9. Howfairis is built for 3.5., 3.6, 3.7. We should drop 3.5 and 3.6 and support 3.8 and 3.9.

**Comment by jspaaks** [comment]
Sure we can try that. Why drop 3.6? 3.5 is no longer supported but 3.6 is, at least security fixes https://en.wikipedia.org/wiki/History_of_Python

**Comment by jspaaks** [comment]
Duplicate of #70, closing this one
