### ISSUE TITLE
Split user and developer documentation

### ISSUE THREAD

**Issue by fdiblen** [fair-software/howfairis#83]
README.md is too long. If we split user and developer documentation, it will greatly help.

**Comment by jspaaks** [comment]
In v0.12, the README is 80% user documentation so I'm not expecting great benefits from moving the 20% to say README.dev.rst, but let's try that and then point to it from README.rst.

**Comment by jspaaks** [comment]
working on it in PR #121

**Comment by jspaaks** [comment]
Unassigning myself so that others can take this up if they want

**Comment by jspaaks** [comment]
PR #121 was merged, closing this issue
