### ISSUE TITLE
Early user engagement

### ISSUE THREAD

**Issue by fdiblen** [fair-software/howfairis#86]
It is a good idea to reach potential users/contributors to get feedback and promote howfairis in early stage.
Some options:
1. Demo it at NLeSC and show how RSEs can use it
1. ~~Presentation at https://sorse.github.io/~~
1. ~~Presentation at https://nl-rse.org/pages/meetups.html~~
1. Contact https://fair-software.eu/ endorsers (https://fair-software.eu/endorse) to inform about the tool and our effort and get feedback / suggestions 
1. Notify RSE Slack channel and the mailing list

**Comment by jspaaks** [comment]
Refs #99 #98 #97
