### ISSUE TITLE
GitHub API rate limiting

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#93]
The GitHub API is used anonymously in this library. If used more than [60 req per hour](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) the API will say no. This limit could be reached when asserting a bunch of software like on https://www.research-software.nl/ .

One way to solve is to use an [OAuth token](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#oauth2-token-sent-in-a-header) which will up the limit to 5000 req per hour. It would be nice if the howfairis tool would allow passing a GitHub OAuth token either as environment variable or as command line argument.

GitLab also has [rate limit](https://docs.gitlab.com/ee/user/gitlab_com/#gitlabcom-specific-rate-limits), but is much higher so not such a problem.

**Comment by jspaaks** [comment]
Agreed, this is something we should fix. It has already been a problem: https://github.com/fair-software/badge/issues/36

**Comment by sverhoeven** [comment]
When recordings are used in tests we should filter the token out of the recording so they don't leak. See https://vcrpy.readthedocs.io/en/latest/advanced.html#filter-sensitive-data-from-the-request

**Comment by jspaaks** [comment]
Issue was auto-closed by fix keyword, reopening

**Comment by jspaaks** [comment]
PR was merged, closing
