### ISSUE TITLE
NL-RSE presentation

### ISSUE THREAD

**Issue by c-martinez** [fair-software/howfairis#97]
On a NL-RSE meetup, we will give a demo of `howfairis` to the NL-RSE community. At this demo we can introduce the motivation for this tool, show the status of the tool as it is at that moment (making it clear that it is still work in progress) and gather input feedback from RSEs (will they use it? what difficulties would they face using it? what additional features they would need? etc.)

Additionally we could do a hands on session in which we help RSEs use `howfairis` on their own software.

**Comment by c-martinez** [comment]
Proposed programme for the session:

| Time | Responsible | Type | Subject |
| --- | ------------ | ---- | ------- |
| 09:30 - 10:00	| Faruk Diblen | Presentation / demo | How FAIR is your software? |
** break **
| 10:15 - 11:30	| Faruk Diblen | Hands-on | How FAIR is your software? |

## Abstracts

### How FAIR is your software?

[howfairis](https://github.com/fair-software/howfairis/) is a Python package to analyze a GitHub or GitLab repository's compliance with the [FAIR software recommendations](http://fair-software.eu/).

In this session we will talk about why FAIR software is important and how to automatically test your software for compliance.

### How FAIR is your software? -- hands-on session

During this session we will focus on applying the howfairis Github Action to your software, to measure how compliant is your software with the FAIR software recommendations. At the end of this session, you will be able to add a badge to your GitHub repository showing to the world how fair your software is!

Prerequisite for this session is to have your software already in a Github repository.

**Comment by fdiblen** [comment]
We want to do this demo in one of the future NL-RSE sessions but not on 10 Feb 2021.

**Comment by jspaaks** [comment]
@fdiblen did it
