### ISSUE TITLE
SORSE

### ISSUE THREAD

**Issue by c-martinez** [fair-software/howfairis#99]
Similar to the NL-RSE engagement (#97), we will do a similar session during SORSE.

In this session we could:
 - Introduce the motivation for this tool
 - Show a demo
 - Gather feedback from RSEs (will they use it? what difficulties would they face using it? what additional features they would need? etc.)

(hands on session in which we help RSEs use howfairis on their own software might not be possible in this setting).

@c-martinez will prepare a submission.

**Comment by c-martinez** [comment]
Submitted -- now waiting for acceptance.

**Comment by sverhoeven** [comment]
Presentation was given by @jspaaks, see https://www.youtube.com/watch?v=7ipy1p-wFo4
